## The calcuation of an inverse of a matrix can be time consuming. 
## Therefore we create a special list object that stores the inverse of a matrix.
## To calculate the inverse of a matrix we define a custom function, that takes
## our special list object as a function argument. It checks whether the list
## contains an inverse matrix and returns it, if it already exists. 
## Only if it does not yet exist will the inverse be calcualted. The result is
## stored in the special list and also returned by the function.  

## This function creates a list that contains functions to set 
## and retrieve the original matrix given to the function as an argument, 
## as well as set and retrieval methods for the inverse of that matrix.

makeCacheMatrix <- function(x = matrix()) {
	m <- NULL
	set <- function(y) {
		x <<- y
		m <<- NULL
	}
	get <- function() x
	setinverse <- function(solve) m <<- solve
	getinverse <- function() m
	list(set = set, get = get, 
		setinverse = setinverse,
		getinverse = getinverse)
}


## This function takes a list object generated by the function makeCacheMatrix(). It will attempt to retrieve the inverse matrix from the list and return it if it already has been calculated. Otherwise it will compute the inverse, store it in the list and also return it. 

cacheSolve <- function(x, ...) {
	## retrieve the cached inverse matrix from the list.
	## If it's not null, return it.
	m <- x$getinverse()
	if(!is.null(m)) {
		message("getting cached data")
		return(m)
	}
	## retrieve the matrix from the list and generate the inverse
	data <- x$get()
	m <- solve(data, ...)
	## cache the inverse 
	x$setinverse(m)
	m
}
